# Generated by Django 5.0.2 on 2024-02-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actor_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshorts',
            name='image',
            field=models.ImageField(null=True, upload_to='movie_shots/'),
        ),
    ]
