# Generated by Django 5.0.2 on 2024-03-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_movieshorts_movieshots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'RatingStar', 'verbose_name_plural': 'RatingStars'},
        ),
    ]
